#!/bin/bash

source /init.sh

uudecode -o input.tar.gz
tar -xf input.tar.gz

echo '[*] Running program...'
cd input

rm -f *.out
for inp in *.in; do
  TEST=${inp:0:-3}
  echo "[*]  Running with \"$TEST\""
  if cat $inp | runas runner runprog ../prog $inp > $TEST.out 2> $TEST.err; then
    echo "[*]   Success!"
  else
    echo "[*]   Failed!"
  fi
done

tar -czf z.tar.gz *.err *.out

uuencode z.tar.gz z.tar.gz >&3
